### ISSUE TITLE
more friendly + consistent interface for utilities

### ISSUE THREAD

**Issue by ethanknox-palmetto** [palmetto/palm-cli#20]
**Context**
Like all good software, palm functionality is made up of a lot of different tools under the hood. things like `click` and `subprocess`.  I would give us a really valuable abstraction layer if `palm` was the single interface to these tools, so we can manage how they play together under the hood, and protect our user's command code from becoming brittle. 

**Is your feature request related to a problem? Please describe.**
I worry about calling interfaces like `click.secho` directly where it clutters the interface, and makes it so we can't upgrade click past breaking versions. let's say click changes the arity in the next version, and we really want to use that version... we can't. not without breaking all our user's existing commands. 

**Describe the solution you'd like**
All these utilities get migrated into palm as thin, highly opinionated wrappers. 
same use case: 
```
from palm.helpers import success_message, fail_message

...
success, msg = ctx.obj.run_in_docker(cmd, env_vars)
delivery = success_message if success else fail_message
delivery(msg)

# in palm/helpers.py
def success_message(msg:str): -> str
    return click.secho(msg, fg="green")
```
then when click decides to deprecate "fg" for "color_name" we can make the fix internally. 

**Describe alternatives you've considered**
keep things pushed to the edge as they are. not as exciting. 

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by jakeberesford-palmetto** [comment]
Yes. I like the direction here. Let's standardize anything we're currently doing with `click.[this_thing]`. The @click decorators might be a little weird to alias in this way, though?
