### ISSUE TITLE
Parameterized docker .env variables no longer auto-populate

### ISSUE THREAD

**Issue by emekdahl-palmetto** [palmetto/palm-cli#27]
**Describe the bug**
Parameterized variables in docker file do not populate as env vars any longer. This is functionality that used to work.

**Your environment**
- `palm` version: 2.1.0
- OS: Mac
- Docker version: Docker version 20.10.10, build b485636, Docker Compose version v2.1.1
- Other dependencies & versions:

**How to reproduce**
Build palm docker container with .env. Run the docker container and `/bin/bash` into it. Use the command `printenv`. Note that parameterized variables are not present.

**Expected behavior**
printenv shows parameterized variables in .env

**Actual behavior**
parameterized variables are not populated (e.g. SNOWFLAKE_USERNAME= )

**Screenshots**

**Additional context**

**Comment by emekdahl-palmetto** [comment]
@ethanknox-palmetto and I paired on this issue to validate it.

**Comment by emekdahl-palmetto** [comment]
Thanks for clarifying, yes, we were running with docker-compose run in addition to using a `palm run` command while validating this bug.

**Comment by jakeberesford-palmetto** [comment]
This seems to be a problem with docker-compose v2.x. The .env files are no longer interpolating `${SOME_ENV_VAR_FROM_YOUR_SHELL}`. There are a lot of [open issues](https://github.com/docker/compose/issues?q=is%3Aissue+is%3Aopen+env) around changes to env vars in compose v2.x. Hopefully, the docker team fixes the issue soon. Otherwise, we will have to change our strategy and implementation for .env files in many, many places.

**Comment by ethanknox-palmetto** [comment]
yep it's a weird one. I think the fix will be quick, docker is about to ask the whole world for a LOT of money so that seems likely; in the meantime I'm going to put together a shim in palm-dbt to patch it using the most common envars for the big 4 data warehouses

**Comment by jakeberesford-palmetto** [comment]
I set up this repo to prove the bug is in docker compose v2.x: https://github.com/jakeberesford-palmetto/docker-compose-env-var-bug

I'm going to submit an issue on docker/compose

**Comment by ethanknox-palmetto** [comment]
I think this is a good time to get away from the dependency on `.env` . The pattern is better served the way we went with palm-dbt where we lean into the compose and use the `.env` explicitly - which is smarter and safer in the end. `.env` goes back to being a place to store values, not define keys.

**Comment by ethanknox-palmetto** [comment]
discussing in #41
