### ISSUE TITLE
Exclude/disable commands via config

### ISSUE THREAD

**Issue by jakeberesford-palmetto** [palmetto/palm-cli#34]
**Context**
Palm commands come from many places. Core, plugins, the repository... and that list is growing!
Some of those commands are useful maybe one time (palm containerize). The rest of the time, those commands are clutter in `palm --help`. 
Some commands may also just not work in your project - for example `palm lint` which uses the `black` library to lint python will not work in a javascript project. Ideally, `palm lint` is overridden by a command that does work. However, in the event that linting is not implemented, a developer on that project should be able to disable that command entirely.

**Is your feature request related to a problem? Please describe.**
When I'm working in an established palm project, I do not want to see irrelevant, or un-useful commands in palm help.

**Describe the solution you'd like**
Allow each project to specify plugins to exclude via palm config. E.g.

```yaml
disable_commands:
- containerize
- init
- lint
```

**Describe alternatives you've considered**
* One-time use commands could potentially be disabled with logic (e.g. is this project already containerized?) however that does not scale well and will not solve the need to disable a command due to incompatibility (e.g. the linting example)

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by emekdahl-palmetto** [comment]
+1

**Comment by ethanknox-palmetto** [comment]
agreed this would be nice to clean things up. so like.. 
```
.palm/config.yml
...
disabled:
    - init
```
