### ISSUE TITLE
move from "docker" to "container" to prepare for podman support

### ISSUE THREAD

**Issue by ethanknox-palmetto** [palmetto/palm-cli#42]
**Context**
Palm relies on containerization. Presently that has been 100% via Docker, but we'd like to expand the ecosystem to a fully OSS offering. 

**Is your feature request related to a problem? Please describe.**
Docker is not OSS and there are limitations, and the learning curve for a thing like podman is not steep but does exist. 
We want to make the switch painless for our users, and we can start by abstracting "Docker" command aliases in palm to "container" commands. then under the hood we can run in the container engine of the user's choice. 

**Describe the solution you'd like**
`run_in_docker` becomes `run_in_container`. Then under the hood we pipe the work to Docker, OR have the ability to use podman instead. 

**Describe alternatives you've considered**
Stick with pure Docker support. Meh. 

**Additional context**
This can start by abstraction and then balancing 100% of requests to a Docker mechanics class for now. That way we can roll podman as seperate work. 

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by ethanknox-palmetto** [comment]
We should alias all these with a deprecation warning, not remove them completely.

**Comment by jakeberesford-palmetto** [comment]
Podman seems like a really strong option and feels like the right pick for our team. But we should keep in mind that there are alternative options that other teams may go with. I've seen some traction around using minikube as a replacement for docker desktop. Ideally, the final state of this implementation would include an abstraction that allows us to support different containerization tools, potentially via plugins or configuration.
