### ISSUE TITLE
Githook for ReadTheDocs

### ISSUE THREAD

**Issue by ethanknox-palmetto** [palmetto/palm-cli#44]
**Context**
ReadTheDocs can automagically deploy when we do via a githook. we should do that.

**Is your feature request related to a problem? Please describe.**
Right now we deploy, then need to remember to manually go to RTD and push the build button :( 

**Describe the solution you'd like**
When we deploy, the githook fires and RTD builds.

**Describe alternatives you've considered**
Keep pushing the button. 

**Additional context**
Whoever does this will need RTD project and repo maintainer access. 

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by jakeberesford-palmetto** [comment]
I just set up the webhook for this - project admins can see it here: https://github.com/palmetto/palm-cli/settings/hooks/331326443/deliveries
