### ISSUE TITLE
Support Modern Docker Compose

### ISSUE THREAD

**Issue by arghmeleg** [palmetto/palm-cli#97]
**Context**
Palm only supports the now deprecated `docker-compose` command, it should support v2 of [docker/compose](https://github.com/docker/compose) using the `docker compose` command.

**Is your feature request related to a problem? Please describe.**
```bash
$ docker compose version
Docker Compose version v2.17.3
$ palm test
Docker Compose is not installed, please install it first
```

**Describe the solution you'd like**
Support `docker compose` (with backwards compatibility for those still using `docker-compose`?)

**Describe alternatives you've considered**
```bash
# /usr/bin/docker-compose
docker compose $@
```

**Additional context**
nope

**Is there an existing feature request for this?**
 * [x]  I have searched the existing issues

**Comment by jakeberesford-palmetto** [comment]
Thanks for opening an issue. We'll get this into a patch release soon. Should have been done long ago!

**Comment by jakeberesford-palmetto** [comment]
@arghmeleg this is released in the latest version of palm. Please `pip install -U palm` to upgrade and let us know if you run into any more trouble!
